"use strict";

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const edge = await readFile(new URL("../supabase/functions/claw-api/index.ts", import.meta.url), "utf8");
const runtime = await readFile(new URL("../web/cloud-runtime.js", import.meta.url), "utf8");
const profile = await readFile(new URL("../web/cloud-profile.js", import.meta.url), "utf8");
const users = await readFile(new URL("../web/cloud-user-management.js", import.meta.url), "utf8");
const app = await readFile(new URL("../web/assets/app.js", import.meta.url), "utf8");
const index = await readFile(new URL("../web/index.html", import.meta.url), "utf8");
const styles = await readFile(new URL("../web/assets/styles.css", import.meta.url), "utf8");
const launcher = await readFile(new URL("./Start_Cloud_Staging.py", import.meta.url), "utf8");
const manualLauncher = await readFile(new URL("../Start_Cloud_Staging.bat", import.meta.url), "utf8");
const devRunner = await readFile(new URL("./dev.mjs", import.meta.url), "utf8");
const manualChecklist = await readFile(new URL("../docs/MANUAL_CLOUD_BROWSER_UAT.md", import.meta.url), "utf8");

for (const route of ["/api/bootstrap", "/api/settings", "/api/machines", "/api/new-closing", "/api/calculate", "/api/closings/save", "/api/refills", "/api/history", "/api/images/replace", "/api/images/remove"]) {
  assert.ok(edge.includes(route), `cloud Edge façade must cover ${route}`);
}
assert.match(edge, /admin\.auth\.getUser\(bearer\)/, "Edge façade must verify the user token");
assert.match(edge, /finalize_daily_closing/, "finalization must use the server-authoritative RPC");
assert.match(edge, /5 \* 1024 \* 1024/, "image size must remain capped at 5 MB");
assert.match(edge, /remove\(\[nextPath\]\)/, "failed image reference updates must clean the new object");
assert.match(runtime, /refresh_token/, "cloud runtime must restore and refresh sessions");
assert.match(runtime, /signOut/, "cloud runtime must support logout");
assert.match(runtime, /shell\.hidden = visible/, "sign-out must hide stale authenticated UI");
assert.match(runtime, /claw-cloud-signed-out/, "session termination must clear the cloud profile surface");
assert.match(runtime, /Username/, "cloud login must present Username, not Email");
assert.match(runtime, /@claw\.internal/, "cloud login must derive an internal Auth identifier");
assert.ok(!/name=\\"email\\"|>Email</.test(runtime), "cloud login must not expose an email field");
assert.match(runtime, /Welcome Back/, "cloud login must render the branded welcome heading");
assert.match(runtime, /Sign in to continue to Claw Closing/, "cloud login must render the product sign-in context");
assert.ok(!runtime.includes("Sign in to staging"), "cloud login must not present a technical staging submit label");
assert.match(runtime, /claw-login-password-toggle/, "cloud login must provide a password visibility control");
assert.match(runtime, /Signing in…/, "cloud login must provide an in-progress state");
assert.match(runtime, /dataset\.submitting/, "cloud login must prevent duplicate submission");
assert.match(runtime, /error\.hidden = false/, "cloud login must render inline authentication errors");
assert.match(runtime, /Unable to sign in right now/, "cloud login must recover from a network error without a browser alert");
assert.match(runtime, /Enter your password/, "cloud login must render a missing-password error inline");
assert.ok(!/Google sign|GitHub sign|Facebook sign|Create Account|Forgot Password/i.test(runtime), "cloud login must remain a controlled company login");
assert.match(styles, /claw-login-card/, "cloud login must use the glass login card treatment");
assert.match(styles, /backdrop-filter:\s*blur\(22px\)/, "cloud login card must use the premium white-glass blur treatment");
assert.match(styles, /width: min\(620px, calc\(100vw - 40px\)\)/, "cloud login card must use the 620px desktop width cap");
assert.match(styles, /min-height: 500px/, "cloud login card must retain the balanced minimum height");
assert.match(styles, /background: rgba\(255, 255, 255, \.94\)/, "cloud login card must use translucent white glass");
assert.ok(!runtime.includes("claw-login-art"), "cloud login must not render decorative artwork layers");
assert.equal((runtime.match(/figma-login\/asset-\d+\.svg/g) || []).length, 0, "cloud login must not reference Figma decorative assets");
assert.ok(!styles.includes("claw-login-shape"), "cloud login stylesheet must not retain decorative artwork positioning");
assert.ok(!runtime.includes("claw-login-environment"), "cloud login must not render a STAGING badge");
assert.ok(!runtime.includes("claw-login-tubes"), "cloud login must remove the superseded two-ribbon artwork layer");
assert.ok(!runtime.includes("claw-login-ribbon"), "cloud login must not retain rejected donut-ribbon elements");
assert.match(styles, /linear-gradient\(135deg, #fff 0%, #fafaf9 48%, #f6f6f4 100%\)/, "cloud login must use the premium light-neutral background");
assert.match(styles, /width: min\(100%, 480px\)/, "login form must be centered within the card at a 480px maximum width");
assert.match(styles, /height: 56px/, "login inputs and submit button must use the polished 56px control height");
assert.match(styles, /background: #111827/, "login submit button must use the professional charcoal treatment");
assert.match(styles, /border-radius: 14px/, "login inputs must use the polished 14px radius");
assert.match(styles, /-webkit-autofill/, "cloud login must neutralize Chrome autofill styling");
assert.match(styles, /stroke-width: 1.8/, "login icons must use one consistent outline stroke weight");
assert.match(users, /Add User/, "Developer UI must provide Add User");
assert.match(users, /Username/, "Developer UI must display Username");
assert.ok(!/>Email<|name=\\"email\\"/.test(users), "Developer UI must not expose technical Auth email");
assert.match(users, /Show inactive/, "Developer UI must hide inactive accounts by default with an explicit toggle");
assert.match(users, /data-user-id/, "Developer UI must expose the existing edit/update action");
assert.match(users, /method: editing \? "PATCH" : "POST"/, "Developer UI must retain create and update API behavior");
assert.match(users, /claw-role-badge/, "Developer UI must render readable role badges");
assert.match(users, /claw-status-badge/, "Developer UI must render readable status badges");
assert.match(users, /validTemporaryPassword/, "Developer UI must validate temporary-password strength before submission");
assert.match(users, /Creating…|Creating/, "Developer UI must show create progress");
assert.match(users, /Saving…|Saving/, "Developer UI must show save progress");
assert.match(users, /state\.users = await request\("\/api\/users"\)/, "Developer UI must refresh authoritative user rows after save");
assert.match(users, /User created\.|User changes saved\./, "Developer UI must confirm a successful create or update");
assert.match(profile, /My Profile/, "cloud profile menu must include My Profile");
assert.match(profile, /Manage Users/, "cloud profile menu must include the Developer action");
assert.match(profile, /profile\.role === "developer"/, "Manage Users must be limited to Developer profile context");
assert.match(profile, /Outlet Access/, "profile dialog must show outlet access");
assert.match(profile, /aria-expanded/, "profile row must expose its menu state");
assert.match(profile, /event\.key !== "Escape"/, "profile menu must close on Escape");
assert.match(profile, /classList\.add\("is-open"\)/, "profile row must show selected/open state");
assert.ok(!profile.includes("@claw.internal"), "profile surface must not expose technical Auth email");
assert.ok(!index.includes("cloud-profile.js"), "LOCAL HTML must not load cloud account code");
assert.match(launcher, /cloud-profile\.js/, "cloud launcher must load the cloud profile surface");
assert.match(styles, /#clawSidebarProfile/, "cloud profile surface must use the sidebar");
assert.match(styles, /claw-staging-indicator/, "STAGING must be a separate header indicator");
assert.match(styles, /claw-sidebar-profile-button\.is-open/, "profile selected state must be styled");
assert.ok(!styles.includes("#clawManageUsersButton"), "old detached Manage Users control must be removed");
assert.ok(!runtime.includes("STAGING · Sign out"), "old floating staging sign-out must not be rendered");
assert.match(app, /adjusted_by: staff/, "cloud refill must send its own Adjusted By value");
assert.match(app, /api\('\/api\/refills'/, "cloud refill must use the dedicated refill mutation");
assert.match(app, /dataset\.submitting/, "modal actions must prevent duplicate submission");
assert.match(edge, /async function recordRefill/, "Edge API must isolate refill behavior from closing save");
assert.match(edge, /Adjusted By is required/, "Edge refill must require its audit operator");
assert.match(edge, /This closing is locked/, "Edge refill must reject finalized or locked closings");
assert.match(edge, /requireClosedBy: false/, "refill draft creation alone may bypass closing staff validation");
assert.match(edge, /created_by_name_snapshot: adjustedBy/, "Edge refill must persist the supplied Adjusted By value");
assert.match(edge, /apply_developer_user_profile/, "Developer-managed users must use the transactional profile/access RPC");
assert.match(edge, /auth\.admin\.deleteUser/, "failed user setup must compensate by removing the new Auth identity");
assert.match(launcher, /CLAW_SUPABASE_PUBLISHABLE_KEY/, "launcher must inject only runtime configuration");
assert.match(launcher, /cloud-staging/, "cloud launcher must declare the canonical cloud runtime mode");
assert.match(launcher, /\("localhost", 3001\)/, "cloud host must use localhost:3001");
assert.match(launcher, /Cache-Control", "no-store"/, "cloud launcher must not retain stale runtime assets");
assert.ok(!runtime.includes("SERVICE_ROLE"), "browser runtime must not contain a service-role key");
assert.match(manualLauncher, /call npm\.cmd run dev:cloud/, "manual launcher must delegate to the canonical cloud command");
assert.match(devRunner, /\.env\.cloud-staging\.local/, "canonical cloud command must use its separate browser-safe config");
assert.match(devRunner, /fbvzqdqjqcbjopuinknw/, "canonical cloud command must pin the approved staging ref");
assert.match(devRunner, /3001/, "canonical cloud command must use localhost:3001");
assert.match(devRunner, /port \$\{port\} is already in use by/, "canonical cloud command must refuse an occupied port");
assert.match(manualChecklist, /localhost:3000\/.*reserved for normal local development/s, "manual cloud UAT must distinguish the reserved local-development port");
assert.ok(!manualLauncher.includes(".env.staging.local"), "manual launcher must not read the server-side staging environment");
assert.match(devRunner, /SERVICE_ROLE\|SECRET\|PASSWORD\|TOKEN/, "canonical cloud command must reject server-only browser config");
for (const item of ["Developer: PASS / FAIL", "Admin: PASS / FAIL", "Outlet A: PASS / FAIL", "Outlet B: PASS / FAIL", "Daily Closing: PASS / FAIL", "Clipboard Paste: PASS / FAIL", "Review: PASS / FAIL", "Print: PASS / FAIL"]) assert.ok(manualChecklist.includes(item), `manual checklist must include ${item}`);
console.log("PASS - cloud Phase 4 façade/runtime contract");
