"use strict";

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const edge = await readFile(new URL("../supabase/functions/claw-api/index.ts", import.meta.url), "utf8");
const runtime = await readFile(new URL("../web/cloud-runtime.js", import.meta.url), "utf8");
const profile = await readFile(new URL("../web/cloud-profile.js", import.meta.url), "utf8");
const users = await readFile(new URL("../web/cloud-user-management.js", import.meta.url), "utf8");
const app = await readFile(new URL("../web/assets/app.js", import.meta.url), "utf8");
const index = await readFile(new URL("../web/index.html", import.meta.url), "utf8");
const styles = await readFile(new URL("../web/assets/styles.css", import.meta.url), "utf8");
const launcher = await readFile(new URL("./Start_Cloud_Staging.py", import.meta.url), "utf8");
const manualLauncher = await readFile(new URL("../Start_Cloud_Staging.bat", import.meta.url), "utf8");
const devRunner = await readFile(new URL("./dev.mjs", import.meta.url), "utf8");
const manualChecklist = await readFile(new URL("../docs/MANUAL_CLOUD_BROWSER_UAT.md", import.meta.url), "utf8");

for (const route of ["/api/bootstrap", "/api/settings", "/api/machines", "/api/new-closing", "/api/calculate", "/api/closings/save", "/api/refills", "/api/history", "/api/images/replace", "/api/images/remove"]) {
  assert.ok(edge.includes(route), `cloud Edge façade must cover ${route}`);
}
assert.match(edge, /admin\.auth\.getUser\(bearer\)/, "Edge façade must verify the user token");
assert.match(edge, /finalize_daily_closing/, "finalization must use the server-authoritative RPC");
assert.match(edge, /5 \* 1024 \* 1024/, "image size must remain capped at 5 MB");
assert.match(edge, /remove\(\[nextPath\]\)/, "failed image reference updates must clean the new object");
assert.match(runtime, /refresh_token/, "cloud runtime must restore and refresh sessions");
assert.match(runtime, /signOut/, "cloud runtime must support logout");
assert.match(runtime, /shell\.hidden = visible/, "sign-out must hide stale authenticated UI");
assert.match(runtime, /claw-cloud-signed-out/, "session termination must clear the cloud profile surface");
assert.match(runtime, /Username/, "cloud login must present Username, not Email");
assert.match(runtime, /@claw\.internal/, "cloud login must derive an internal Auth identifier");
assert.ok(!/name=\\"email\\"|>Email</.test(runtime), "cloud login must not expose an email field");
assert.match(runtime, /Welcome Back/, "cloud login must render the branded welcome heading");
assert.match(runtime, /Sign in to continue to Claw Closing/, "cloud login must render the product sign-in context");
assert.ok(!runtime.includes("Sign in to staging"), "cloud login must not present a technical staging submit label");
assert.match(runtime, /claw-login-password-toggle/, "cloud login must provide a password visibility control");
assert.match(runtime, /Signing in…/, "cloud login must provide an in-progress state");
assert.match(runtime, /dataset\.submitting/, "cloud login must prevent duplicate submission");
assert.match(runtime, /error\.hidden = false/, "cloud login must render inline authentication errors");
assert.match(runtime, /Unable to sign in right now/, "cloud login must recover from a network error without a browser alert");
assert.match(runtime, /Enter your password/, "cloud login must render a missing-password error inline");
assert.ok(!/Google sign|GitHub sign|Facebook sign|Create Account|Forgot Password/i.test(runtime), "cloud login must remain a controlled company login");
assert.match(styles, /claw-login-card/, "cloud login must use the glass login card treatment");
assert.match(styles, /backdrop-filter:\s*blur\(36px\) saturate\(135%\)/, "cloud login card must use the light reference frosted-glass treatment");
assert.match(styles, /width: min\(79.4vw, 1525px\)/, "cloud login card must preserve the 1525px/79.4vw desktop reference proportion");
assert.match(styles, /min-height: min\(64vh, 690px\)/, "cloud login card must preserve the 690px desktop reference height");
assert.match(styles, /rgba\(255, 255, 255, \.52\)/, "cloud login card must be translucent light glass");
assert.match(runtime, /claw-login-tubes/, "cloud login must render the organic tube artwork layer");
assert.match(runtime, /<svg class="claw-login-tubes"/, "cloud login artwork must use SVG paths rather than CSS ring shapes");
assert.match(runtime, /stroke-linecap="round"/, "cloud login tube paths must have smooth organic endpoints");
assert.ok(!runtime.includes("claw-login-ribbon"), "cloud login must not retain rejected donut-ribbon elements");
assert.match(styles, /#f8f7fb/, "cloud login must retain the light lavender reference base");
assert.match(runtime, /#f4d500/i, "cloud login artwork must use the JOLI POLI yellow palette");
assert.match(styles, /left: 50%/, "desktop login form must remain grouped on the right half of the glass panel");
assert.match(styles, /width: 388px/, "desktop login form group must preserve the reference width");
assert.match(styles, /height: 52px/, "login inputs and submit button must preserve the reference control height");
assert.match(styles, /background: #171725/, "login submit button must retain the dark reference action color");
assert.match(users, /Add User/, "Developer UI must provide Add User");
assert.match(users, /Username/, "Developer UI must display Username");
assert.ok(!/>Email<|name=\\"email\\"/.test(users), "Developer UI must not expose technical Auth email");
assert.match(users, /Show inactive/, "Developer UI must hide inactive accounts by default with an explicit toggle");
assert.match(users, /data-user-id/, "Developer UI must expose the existing edit/update action");
assert.match(users, /method: editing \? "PATCH" : "POST"/, "Developer UI must retain create and update API behavior");
assert.match(users, /claw-role-badge/, "Developer UI must render readable role badges");
assert.match(users, /claw-status-badge/, "Developer UI must render readable status badges");
assert.match(users, /validTemporaryPassword/, "Developer UI must validate temporary-password strength before submission");
assert.match(users, /Creating…|Creating/, "Developer UI must show create progress");
assert.match(users, /Saving…|Saving/, "Developer UI must show save progress");
assert.match(users, /state\.users = await request\("\/api\/users"\)/, "Developer UI must refresh authoritative user rows after save");
assert.match(users, /User created\.|User changes saved\./, "Developer UI must confirm a successful create or update");
assert.match(profile, /My Profile/, "cloud profile menu must include My Profile");
assert.match(profile, /Manage Users/, "cloud profile menu must include the Developer action");
assert.match(profile, /profile\.role === "developer"/, "Manage Users must be limited to Developer profile context");
assert.match(profile, /Outlet Access/, "profile dialog must show outlet access");
assert.match(profile, /aria-expanded/, "profile row must expose its menu state");
assert.match(profile, /event\.key !== "Escape"/, "profile menu must close on Escape");
assert.match(profile, /classList\.add\("is-open"\)/, "profile row must show selected/open state");
assert.ok(!profile.includes("@claw.internal"), "profile surface must not expose technical Auth email");
assert.match(index, /cloud-profile\.js/, "cloud profile surface must be loaded with the cloud runtime");
assert.match(styles, /#clawSidebarProfile/, "cloud profile surface must use the sidebar");
assert.match(styles, /claw-staging-indicator/, "STAGING must be a separate header indicator");
assert.match(styles, /claw-sidebar-profile-button\.is-open/, "profile selected state must be styled");
assert.ok(!styles.includes("#clawManageUsersButton"), "old detached Manage Users control must be removed");
assert.ok(!runtime.includes("STAGING · Sign out"), "old floating staging sign-out must not be rendered");
assert.match(app, /adjusted_by: staff/, "cloud refill must send its own Adjusted By value");
assert.match(app, /api\('\/api\/refills'/, "cloud refill must use the dedicated refill mutation");
assert.match(app, /dataset\.submitting/, "modal actions must prevent duplicate submission");
assert.match(edge, /async function recordRefill/, "Edge API must isolate refill behavior from closing save");
assert.match(edge, /Adjusted By is required/, "Edge refill must require its audit operator");
assert.match(edge, /This closing is locked/, "Edge refill must reject finalized or locked closings");
assert.match(edge, /requireClosedBy: false/, "refill draft creation alone may bypass closing staff validation");
assert.match(edge, /created_by_name_snapshot: adjustedBy/, "Edge refill must persist the supplied Adjusted By value");
assert.match(edge, /apply_developer_user_profile/, "Developer-managed users must use the transactional profile/access RPC");
assert.match(edge, /auth\.admin\.deleteUser/, "failed user setup must compensate by removing the new Auth identity");
assert.match(launcher, /CLAW_SUPABASE_PUBLISHABLE_KEY/, "launcher must inject only runtime configuration");
assert.match(launcher, /\("localhost", 3001\)/, "cloud host must use localhost:3001");
assert.match(launcher, /Cache-Control", "no-store"/, "cloud launcher must not retain stale runtime assets");
assert.ok(!runtime.includes("SERVICE_ROLE"), "browser runtime must not contain a service-role key");
assert.match(manualLauncher, /call npm\.cmd run dev:cloud/, "manual launcher must delegate to the canonical cloud command");
assert.match(devRunner, /\.env\.cloud-staging\.local/, "canonical cloud command must use its separate browser-safe config");
assert.match(devRunner, /fbvzqdqjqcbjopuinknw/, "canonical cloud command must pin the approved staging ref");
assert.match(devRunner, /3001/, "canonical cloud command must use localhost:3001");
assert.match(devRunner, /port \$\{port\} is already in use by/, "canonical cloud command must refuse an occupied port");
assert.match(manualChecklist, /localhost:3000\/.*reserved for normal local development/s, "manual cloud UAT must distinguish the reserved local-development port");
assert.ok(!manualLauncher.includes(".env.staging.local"), "manual launcher must not read the server-side staging environment");
assert.match(devRunner, /SERVICE_ROLE\|SECRET\|PASSWORD\|TOKEN/, "canonical cloud command must reject server-only browser config");
for (const item of ["Developer: PASS / FAIL", "Admin: PASS / FAIL", "Outlet A: PASS / FAIL", "Outlet B: PASS / FAIL", "Daily Closing: PASS / FAIL", "Clipboard Paste: PASS / FAIL", "Review: PASS / FAIL", "Print: PASS / FAIL"]) assert.ok(manualChecklist.includes(item), `manual checklist must include ${item}`);
console.log("PASS - cloud Phase 4 façade/runtime contract");
